import type { Metadata } from "next";
import "./globals.css";
import Header from "@/features/nav/Header";
import Footer from "@/features/nav/Footer";
import Layout from "@/features/Layout";

export const metadata: Metadata = {
  title: "야놀자리서치",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <body>
        <Header />
        <Layout>
          {children}
        </Layout>
        <Footer />
      </body>
    </html>
  );
}
